services:
  postgres-keycloakdb:
    container_name: postgres-keycloakdb
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloakdb
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak-DB66
  keycloak:
    container_name: keycloak-shop
    image: quay.io/keycloak/keycloak:25.0.6
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_USER: keycloak
      DB_PASSWORD: keycloak-DB66
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-KC66
    ports:
      - 8181:8080
    volumes:
      - ./docker/keycloak/realm/:/opt/keycloak/data/import/
    depends_on:
      - postgres-keycloakdb
volumes:
  db:
    driver: local