spring:
  application:
    name: gateway-service
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      filter:
        secure-headers:
          disabled: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product
            - Method=GET,POST
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order
            - Method=GET,POST
eureka:
  client:
    name: gateway-service
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  ssl:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
