spring:
  application:
    name: gateway-service
eureka:
  client:
    name: gateway-service
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  ssl:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
