services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=robert
      - POSTGRES_PASSWORD=postgreSQL66
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local