server:
  port: 9000

routing:
  docs-path: /api-docs
  routes:
    - name: product_service
      url: http://localhost:8080
      path: /api/product
      circuit-breaker: productServiceCircuitBreaker
      swagger:
        name: product_service_swagger
        path: /aggregate/product-service/v3/api-docs
        circuit-breaker: productServiceSwaggerCircuitBreaker
    - name: order_service
      url: http://localhost:8081
      path: /api/order
      circuit-breaker: orderServiceCircuitBreaker
      swagger:
        name: order_service_swagger
        path: /aggregate/order-service/v3/api-docs
        circuit-breaker: orderServiceSwaggerCircuitBreaker
    - name: inventory_service
      url: http://localhost:8082
      path: /api/inventory
      circuit-breaker: inventoryServiceCircuitBreaker
      swagger:
        name: inventory_service_swagger
        path: /aggregate/inventory-service/v3/api-docs
        circuit-breaker: inventoryServiceSwaggerCircuitBreaker
    - name: fallbackRoute
      url: forward:/fallbackRoute
      path: /fallbackRoute

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shop-security-realm

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /api-docs

# Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://localhost:3100/loki/api/v1/push

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
